import { Injectable } from '@nestjs/common';
import { DatabaseService } from '../database/database.service';
import {
  createEmployeeSkillRelationsTableSql,
  createEmployeesTableSql,
  createSkillsTableSql,
  deleteEmployeeSkillRelationsTableSql,
  deleteEmployeesTableSql,
  deleteSkillsTableSql,
  dropEmployeeSkillRelationsTableSql,
  dropEmployeesTableSql,
  dropSkillsTableSql,
  insertEmployeeSql,
  insertSkillSql,
} from '../sql-commands';

@Injectable()
export class TablesService {
  constructor(protected readonly databaseService: DatabaseService) {}

  async createTables() {
    await this.databaseService.execute(createEmployeesTableSql);
    await this.databaseService.execute(createSkillsTableSql);
    await this.databaseService.execute(createEmployeeSkillRelationsTableSql);
  }

  async deleteData() {
    await this.databaseService.execute(deleteEmployeeSkillRelationsTableSql);
    await this.databaseService.execute(deleteEmployeesTableSql);
    await this.databaseService.execute(deleteSkillsTableSql);
  }

  async dropTables() {
    await this.databaseService.execute(dropEmployeeSkillRelationsTableSql);
    await this.databaseService.execute(dropEmployeesTableSql);
    await this.databaseService.execute(dropSkillsTableSql);
  }

  async populateTables() {
    for (const employee of sampleEmployees) {
      await this.databaseService.execute(insertEmployeeSql, {
        name: employee.name,
      });
    }

    for (const skill of sampleSkills) {
      await this.databaseService.execute(insertSkillSql, {
        name: skill.name,
      });
    }
  }
}

const sampleEmployees = [
  { name: 'Adele' },
  { name: 'Laura Marling' },
  { name: 'Zayn Malik' },
  { name: 'Emily Maguire' },
  { name: 'Amy Macdonald' },
  { name: 'Kirsty MacColl' },
  { name: 'Ewan MacColl' },
  { name: 'Nick Lowe' },
  { name: 'Jez Lowe' },
  { name: 'Cher Lloyd' },
  { name: 'Dua Lipa' },
  { name: 'Leona Lewis' },
  { name: 'Al Lewis' },
  { name: 'Adam Leonardo' },
  { name: 'John Lennon' },
  { name: 'Charlie Landsborough' },
  { name: 'Steve Knightley' },
  { name: 'Beverley Knight' },
  { name: 'Hani King' },
  { name: 'Nik Kershaw' },
  { name: 'Martyn Joseph' },
  { name: 'Johnny Marr' },
  { name: 'Wizz Jones' },
  { name: 'Michael Marra' },
  { name: 'Brian May' },
  { name: 'Sam Smith' },
  { name: 'Lucie Silvas' },
  { name: 'Ed Sheeran' },
  { name: 'Emeli Sandé' },
  { name: 'Ricky Ross' },
  { name: 'Paul Poulton' },
  { name: 'Mal Pope' },
  { name: 'Karen Poole' },
  { name: 'Liam Payne' },
  { name: 'Passenger' },
  { name: 'Ozzy Osbourne' },
  { name: 'Tom Odell' },
  { name: 'John Newman' },
  { name: 'Graham Nash' },
  { name: 'James Morrison' },
  { name: 'Gary Moore' },
  { name: 'Mika' },
  { name: 'Shelagh McDonald' },
  { name: 'Paul McCartney' },
  { name: 'Conor Maynard' },
  { name: 'John Martyn' },
  { name: 'Tom Jones' },
  { name: 'Elton John' },
  { name: 'Bert Jansch' },
  { name: 'Marina Diamandis' },
  { name: 'Chris de Burgh' },
  { name: 'Alex Day' },
  { name: 'Paul Stuart Davies' },
  { name: 'Gareth Davies' },
  { name: 'Elvis Costello' },
  { name: 'Lloyd Cole' },
  { name: 'Gary Clark' },
  { name: 'Kate Bush' },
  { name: 'Melanie Brown' },
  { name: 'Andy Brown' },
  { name: 'David Bowie' },
  { name: 'James Blunt' },
  { name: 'Matt Bigland' },
  { name: 'James Bay' },
  { name: 'Rich Batsford' },
  { name: 'Gary Barlow' },
  { name: 'Kevin Ayers' },
  { name: 'Joan Armatrading' },
  { name: 'Lauren Aquilina' },
  { name: 'Lily Allen' },
  { name: 'Siobhán Donaghy' },
  { name: 'Donovan' },
  { name: 'Josh Doyle' },
  { name: 'Duffy' },
  { name: 'Jamelia' },
  { name: 'Ben Howard' },
  { name: 'Trevor Horn' },
  { name: 'Robyn Hitchcock' },
  { name: 'Boo Hewerdine' },
  { name: 'Ant Henson' },
  { name: 'Ella Henderson' },
  { name: 'Paul Heaton' },
  { name: 'Imogen Heap' },
  { name: 'Justin Hayward' },
  { name: 'Cat Stevens' },
  { name: 'PJ Harvey' },
  { name: 'Nick Harper' },
  { name: 'Malcolm Guite' },
  { name: 'David Gray' },
  { name: 'Ellie Goulding' },
  { name: 'Maurice Gibb' },
  { name: 'Andi Fraggs' },
  { name: 'Kat Flint' },
  { name: 'Newton Faulkner' },
  { name: 'Ella Eyre' },
  { name: 'George Harrison' },
  { name: 'Harry Styles' },
];

const sampleSkills = [
  { name: 'Object Rexx' },
  { name: 'Oberon' },
  { name: 'NXT-G' },
  { name: 'NSIS' },
  { name: 'NQC' },
  { name: 'Nemerle' },
  { name: 'NATURAL' },
  { name: 'MUMPS' },
  { name: 'MS-DOS batch' },
  { name: 'Moto' },
  { name: 'MOO' },
  { name: 'Monkey' },
  { name: 'Modula-3' },
  { name: 'Modula-2' },
  { name: 'Miva' },
  { name: 'Mercury' },
  { name: 'MEL' },
  { name: 'MDX' },
  { name: 'Max/MSP' },
  { name: 'MATLAB' },
  { name: 'Occam' },
  { name: 'Maple' },
  { name: 'OpenCL' },
  { name: 'PHP' },
  { name: 'X10' },
  { name: 'Wolfram' },
  { name: 'Whitespace' },
  { name: 'VHDL' },
  { name: 'Verilog' },
  { name: 'VBScript' },
  { name: 'TypeScript' },
  { name: 'Swift' },
  { name: 'Squirrel' },
  { name: 'Squeak' },
  { name: 'SPARK' },
  { name: 'Smalltalk' },
  { name: 'Scratch' },
  { name: 'Scala' },
  { name: 'SAS' },
  { name: 'Ruby' },
  { name: 'Q' },
  { name: 'Python' },
  { name: 'Prolog' },
  { name: 'PowerShell' },
  { name: 'PL/SQL' },
  { name: 'Perl' },
  { name: 'xBase' },
  { name: 'MANTIS' },
  { name: 'Magik' },
  { name: 'Fortran' },
  { name: 'Fantom' },
  { name: 'EXEC' },
  { name: 'Etoys' },
  { name: 'Erlang' },
  { name: 'Elm' },
  { name: 'Eiffel' },
  { name: 'ECMAScript' },
  { name: 'Curl' },
  { name: 'Common Lisp' },
  { name: 'COMAL' },
  { name: 'CoffeeScript' },
  { name: 'COBOL' },
  { name: 'Caml' },
  { name: 'C++' },
  { name: 'Boo' },
  { name: 'Bash' },
  { name: 'AutoLISP' },
  { name: 'Applescript' },
  { name: 'Apex' },
  { name: 'Fortress' },
  { name: 'Malbolge' },
  { name: 'Gambas' },
  { name: 'Hack' },
  { name: 'Lustre' },
  { name: 'LPC' },
  { name: 'LotusScript' },
  { name: 'Lisp' },
  { name: 'Lingo' },
  { name: 'Limbo' },
  { name: 'Lasso' },
  { name: 'Ladder Logic' },
  { name: 'LabVIEW' },
  { name: 'Kotlin' },
  { name: 'JScript.NET' },
  { name: 'JScript' },
  { name: 'JavaFX Script' },
  { name: 'Java' },
  { name: 'JADE' },
  { name: 'INTERCAL' },
  { name: 'Inform' },
  { name: 'HyperTalk' },
  { name: 'Heron' },
  { name: 'Haxe' },
  { name: 'Haskell' },
  { name: 'GNU Octave' },
  { name: 'XQuery' },
  { name: 'Angelscript 4' },
];
